#!/usr/bin/env python
import matplotlib.pyplot as plt
import itertools
import progressbar

def isa_group_separator( line ):
    return line=='\n'


all_lines = []

with open( 'data/halo_lines.txt', 'r' ) as f:
    for key, group in itertools.groupby( f, isa_group_separator):
        if not key:
            line = []
            for record in group:
                z, x = map( float, record.split() )
                line.append( (z - 12000,x ) )
            if len(line) > 5 :
                all_lines.append( list(zip( *line ) ) )


fig = plt.figure( figsize = [6, 5] )
fig.set_tight_layout(True)
ax = fig.add_subplot( 111 )
ax.set_rasterization_zorder(1);
ax.grid( True )
ax.set_xlim( -12000, -2000 )
ax.set_ylim( -500, 500 )
ax.set_xlabel( 'z (cm)' )
ax.set_ylabel( 'x (cm)' )

nlines = 10000
with progressbar.ProgressBar( maxval = nlines )  as pb:
    for i,line in enumerate(all_lines[0:nlines]):
        pb.update( i )
        ax.plot( line[0], line[1], color = 'DarkBlue',
                alpha = 0.02, zorder = 0 ) 

print( "Saving ... " )
plt.savefig( 'output/mc_tracks_zx.pdf', format = 'pdf', transparent = 'false' )
