#!/usr/bin/env python
import matplotlib.colors

hsvcolors = [ ( 0.6, 1, 0 ), ( 0.6, 0.75, 0.30 ), (0.6, 0.5, 0.60, ), (0.6, 0.25, 0.90 ), (0.2, 0.5, 0.5) ]
colors = [ matplotlib.colors.rgb2hex(matplotlib.colors.hsv_to_rgb( cl )) for cl in hsvcolors ]
print (colors)
